lines.push('');
lines.push('## DIAGRAM 4: Database Relationships');
lines.push('`mermaid');
lines.push('erDiagram');
lines.push('  USER ||--o{ BUSINESS : owns');
lines.push('  BUSINESS ||--o{ ITEM : has');
lines.push('  ITEM ||--o{ REVIEW : receives');
lines.push('  USER ||--o{ REVIEW : writes');
lines.push('  REVIEW ||--o{ REACTION : gets');
lines.push('  REVIEW ||--o{ REPLY : has');
lines.push('  USER ||--o{ FOLLOW : follows');
lines.push('  USER ||--o{ NOTIFICATION : receives');
lines.push('  USER {');
lines.push('    string role');
lines.push('    number trustScore');
lines.push('    string googleId');
lines.push('  }');
lines.push('  REVIEW {');
lines.push('    number rating');
lines.push('    boolean isPermanent');
lines.push('    string reviewType');
lines.push('  }');
lines.push('  ITEM {');
lines.push('    number price');
lines.push('    string availability');
lines.push('  }');
lines.push('`');
lines.push('');
lines.push('---');
